"""
Compare downstream QSAR model performance under SAE (similarity-aware) split
vs. plain random split, on the IC50_EGFR demo dataset.

For each split, a RandomForestRegressor is trained on Morgan fingerprints of
the training molecules and evaluated on the held-out test molecules. The SAE
split forces train/test molecules to be dissimilar (or to follow a target
similarity distribution), which is expected to give a *harder*, more
realistic estimate of generalization than a random split, where near-duplicate
molecules can leak between train and test.
"""
import os
import random
import json
import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit import RDLogger
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from scipy.stats import pearsonr, spearmanr

RDLogger.DisableLog('rdApp.*')

DATASET_PATH = 'demo_input/IC50_EGFR.csv'
SAE_TRAIN = (
    'demo_output/IC50_EGFR/'
    'sigmoid-True_base-lr-1.00e-02_optim-kind-ExtraAdam_sched-kind-CosineAnnealing_'
    'init-kind-custom_lamb-2.03e-03_sigma-0.10_scale-factor-100_bins-89e6b15907a9354ec4caf6e18ce378db_'
    'seed-233_init-scale-5_max-iters-20000/train.csv'
)
SAE_TEST = (
    'demo_output/IC50_EGFR/'
    'sigmoid-True_base-lr-1.00e-02_optim-kind-ExtraAdam_sched-kind-CosineAnnealing_'
    'init-kind-custom_lamb-2.03e-03_sigma-0.10_scale-factor-100_bins-89e6b15907a9354ec4caf6e18ce378db_'
    'seed-233_init-scale-5_max-iters-20000/test.csv'
)
RANDOM_SPLIT_DIR = 'demo_output/IC50_EGFR_random_split'
RANDOM_SEEDS = [233, 234, 235, 236, 237]
TEST_RATIO = 0.2
RESULTS_PATH = 'demo_output/split_comparison_results.json'


def make_random_split(data_table, test_ratio, seed):
    n = len(data_table)
    inds = list(range(n))
    random.Random(seed).shuffle(inds)
    n_test = int(round(n * test_ratio))
    test_inds = inds[:n_test]
    train_inds = inds[n_test:]
    return data_table.iloc[train_inds], data_table.iloc[test_inds]


def morgan_fp(smi, radius=2, n_bits=2048):
    mol = Chem.MolFromSmiles(smi)
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=n_bits)
    arr = np.zeros((n_bits,), dtype=np.int8)
    for bit in fp.GetOnBits():
        arr[bit] = 1
    return arr


def featurize(table):
    X = np.stack([morgan_fp(smi) for smi in table[0]])
    y = table[1].to_numpy(dtype=float)
    return X, y


def evaluate(train_table, test_table, seed=0):
    X_train, y_train = featurize(train_table)
    X_test, y_test = featurize(test_table)
    model = RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=seed)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    rmse = mean_squared_error(y_test, y_pred) ** 0.5
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    pearson_r = pearsonr(y_test, y_pred)[0]
    spearman_r = spearmanr(y_test, y_pred)[0]
    return {
        'n_train': len(train_table), 'n_test': len(test_table),
        'rmse': rmse, 'mae': mae, 'r2': r2,
        'pearson_r': pearson_r, 'spearman_r': spearman_r,
    }


def main():
    data_table = pd.read_csv(DATASET_PATH, header=None)
    print(f'Full dataset: {len(data_table)} molecules')

    # --- SAE split (already generated by SAE_split.py) ---
    sae_train = pd.read_csv(SAE_TRAIN, header=None)
    sae_test = pd.read_csv(SAE_TEST, header=None)
    print(f'\n[SAE split] train={len(sae_train)} test={len(sae_test)}')
    sae_metrics = evaluate(sae_train, sae_test, seed=42)
    print('  ', sae_metrics)

    # --- Random splits (multiple seeds for a robust estimate) ---
    os.makedirs(RANDOM_SPLIT_DIR, exist_ok=True)
    random_runs = []
    for seed in RANDOM_SEEDS:
        train_table, test_table = make_random_split(data_table, TEST_RATIO, seed)
        seed_dir = f'{RANDOM_SPLIT_DIR}/seed-{seed}'
        os.makedirs(seed_dir, exist_ok=True)
        train_table.to_csv(f'{seed_dir}/train.csv', index=False, header=False)
        test_table.to_csv(f'{seed_dir}/test.csv', index=False, header=False)
        print(f'\n[Random split seed={seed}] train={len(train_table)} test={len(test_table)}')
        m = evaluate(train_table, test_table, seed=42)
        print('  ', m)
        random_runs.append(m)

    random_agg = {
        key: {
            'mean': float(np.mean([r[key] for r in random_runs])),
            'std': float(np.std([r[key] for r in random_runs])),
        }
        for key in ['rmse', 'mae', 'r2', 'pearson_r', 'spearman_r']
    }

    results = {
        'sae_split': sae_metrics,
        'random_split_runs': random_runs,
        'random_split_agg': random_agg,
    }
    with open(RESULTS_PATH, 'w') as f:
        json.dump(results, f, indent=2)

    print('\n' + '=' * 60)
    print(f"{'metric':12s} {'SAE split':>12s} {'random split (mean±std)':>28s}")
    for key in ['rmse', 'mae', 'r2', 'pearson_r', 'spearman_r']:
        agg = random_agg[key]
        print(f"{key:12s} {sae_metrics[key]:12.4f} {agg['mean']:12.4f} +/- {agg['std']:.4f}")
    print('=' * 60)
    print(f'Saved results to {RESULTS_PATH}')


if __name__ == '__main__':
    main()
